-- Migration: Seed Career Practice demo class
-- Created: 2026-02-05
-- Purpose: Create default class for new user onboarding

-- Create Career Practice class owned by Sarah Johnson (existing teacher)
-- Note: class_code is auto-generated by the database
INSERT INTO classes (name, description, teacher_id)
SELECT 
  'Career Practice',
  'Practice your soft skills with AI-powered feedback. Perfect for job interviews, presentations, and professional communication.',
  t.id
FROM teachers t
WHERE t.email = 'sarah.johnson@university.edu'
AND NOT EXISTS (
  SELECT 1 FROM classes WHERE name = 'Career Practice'
);

-- Add RLS policy to allow students to enroll themselves in classes
-- This is needed for the auto-enrollment feature
DO $$
BEGIN
  -- Check if policy exists before creating
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'class_enrollments' 
    AND policyname = 'Students can enroll themselves'
  ) THEN
    CREATE POLICY "Students can enroll themselves" ON class_enrollments
      FOR INSERT
      WITH CHECK (true);
  END IF;
END $$;

-- Add RLS policy to allow reading classes (for enrollment lookup)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'classes' 
    AND policyname = 'Anyone can view classes'
  ) THEN
    CREATE POLICY "Anyone can view classes" ON classes
      FOR SELECT
      USING (true);
  END IF;
END $$;

-- Log success
DO $$
DECLARE
  career_practice_id UUID;
  class_code_val VARCHAR(8);
  teacher_name_val VARCHAR(255);
BEGIN
  SELECT c.id, c.class_code, t.name 
  INTO career_practice_id, class_code_val, teacher_name_val
  FROM classes c
  JOIN teachers t ON c.teacher_id = t.id
  WHERE c.name = 'Career Practice';
  
  IF career_practice_id IS NOT NULL THEN
    RAISE NOTICE 'Career Practice class ready - ID: %, Code: %, Owner: %', career_practice_id, class_code_val, teacher_name_val;
  ELSE
    RAISE WARNING 'Career Practice class was NOT created. Make sure sarah.johnson@university.edu exists in teachers table.';
  END IF;
END $$;
