-- Migration: Seed Career Practice demo class
-- Created: 2026-02-05
-- Purpose: Create default teacher and class for new user onboarding

-- Insert Sarah Johnson as demo teacher (if not exists)
INSERT INTO teachers (name, email)
VALUES ('Sarah Johnson', 'sarah.johnson@speakeasy.demo')
ON CONFLICT (email) DO NOTHING;

-- Create Career Practice class owned by Sarah Johnson (if not exists)
-- Note: class_code is auto-generated by the database
INSERT INTO classes (name, description, teacher_id)
SELECT 
  'Career Practice',
  'Practice your soft skills with AI-powered feedback. Perfect for job interviews, presentations, and professional communication.',
  t.id
FROM teachers t
WHERE t.email = 'sarah.johnson@speakeasy.demo'
AND NOT EXISTS (
  SELECT 1 FROM classes WHERE name = 'Career Practice'
);

-- Add RLS policy to allow students to enroll themselves in classes
-- This is needed for the auto-enrollment feature
DO $$
BEGIN
  -- Check if policy exists before creating
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'class_enrollments' 
    AND policyname = 'Students can enroll themselves'
  ) THEN
    CREATE POLICY "Students can enroll themselves" ON class_enrollments
      FOR INSERT
      WITH CHECK (true);
  END IF;
END $$;

-- Add RLS policy to allow reading classes (for enrollment lookup)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies 
    WHERE tablename = 'classes' 
    AND policyname = 'Anyone can view classes'
  ) THEN
    CREATE POLICY "Anyone can view classes" ON classes
      FOR SELECT
      USING (true);
  END IF;
END $$;

-- Log success
DO $$
DECLARE
  career_practice_id UUID;
  class_code_val VARCHAR(8);
BEGIN
  SELECT id, class_code INTO career_practice_id, class_code_val
  FROM classes WHERE name = 'Career Practice';
  
  IF career_practice_id IS NOT NULL THEN
    RAISE NOTICE 'Career Practice class created/exists with ID: % and code: %', career_practice_id, class_code_val;
  END IF;
END $$;
